---
abstract: 'Transparent BigNumber support for Perl'
author:
  - '(C) by Tels L<http://bloodgate.com/> in early 2002 - 2007.'
  - 'Tels <nospam-abuse@bloodgate.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.62
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 1.01'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: bignum
no_index:
  directory:
    - inc
    - t
requires:
  Math::BigInt: 1.88
  Math::BigRat: 0.21
  perl: 5.006
resources:
  license: http://dev.perl.org/licenses/
version: 0.29
