--- #YAML:1.0
name: bignum
version: 0.16
version_from: lib/bignum.pm
license: perl
distribution_type: module
generated_by: bignum version 0.16
installdirs: perl
requires:
  Math::BigFloat: 1.48
  Math::BigInt: 1.74
  Math::BigRat: 0.14
