---
abstract: unknown
author:
  - 'Peter John Acklam <pjacklam@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.24, CPAN::Meta::Converter version 2.150010'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: bignum
no_index:
  directory:
    - t
    - inc
requires:
  Math::BigInt: '1.999718'
  Math::BigRat: '0.12'
  Test::More: '0.47'
  perl: '5.006'
version: '0.45'
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
